# Generated by Django 3.2.5 on 2022-05-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_image', models.ImageField(upload_to='')),
                ('second_image', models.ImageField(blank=True, upload_to='')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('recognition_image_1', models.ImageField(null=True, upload_to='')),
                ('recognition_image_2', models.ImageField(null=True, upload_to='')),
                ('detect_image', models.ImageField(upload_to='')),
                ('faces', models.IntegerField()),
                ('accuracy', models.FloatField(null=True)),
                ('time', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.record')),
            ],
        ),
    ]
