# Generated by Django 4.2.8 on 2023-12-25 19:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('noise_type', models.CharField(choices=[('gaussian', 'Gauss Noise'), ('laplacian', 'Laplacian Noise'), ('poisson', 'Poisson Noise'), ('impulse', 'Impulse Noise'), ('none', 'No Noise')], default='none', max_length=10)),
                ('noise_applied', models.BooleanField(default=False)),
                ('attenuate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('recognition_image_1', models.ImageField(null=True, upload_to='')),
                ('recognition_image_2', models.ImageField(null=True, upload_to='')),
                ('faces', models.IntegerField()),
                ('euclidian_distance', models.FloatField(null=True)),
                ('time', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
